services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-database
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    restart: unless-stopped

  frontend:
    image: client:1.0-sgu
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    container_name: sgu-frontend
    ports:
      - "3000:3000"
    networks:
      - sgu-net
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080

  backend:
    image: server:1.0-sgu
    build:
      context: ./server
    container_name: sgu-backend
    environment:
      SERVER_PORT: 82
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu-demo
      DB_USER: root
      DB_PASS: root
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    depends_on:
      - database

volumes:
  sgu-volume:
    external: true

networks:
  sgu-net:
    external: true
